# Generated by Django 3.2 on 2022-03-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'пользователя', 'verbose_name_plural': 'пользователи'},
        ),
    ]
