# Generated by Django 3.2 on 2022-03-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_user_todo_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('pk',), 'verbose_name': 'проект', 'verbose_name_plural': 'проекты'},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('pk',), 'verbose_name': 'заметку', 'verbose_name_plural': 'заметки'},
        ),
    ]
