# Generated by Django 3.2 on 2022-03-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20220306_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='ПРИЗНАК ОТКРЫТОСТИ'),
        ),
    ]
