# Generated by Django 3.2 on 2022-03-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20220308_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.TextField(blank=True, verbose_name='ТЕКСТ ЗАМЕТКИ'),
        ),
    ]
